SHOW TABLES;

-- DESCRIBE TABLES
DESCRIBE ADD_TO_CART;
DESCRIBE CART;
DESCRIBE CHECKOUT;
DESCRIBE CUSTOMER;
DESCRIBE CUSTOMER_PHONE;
DESCRIBE CUSTOMER_SUPPORT;
DESCRIBE ORDERS;
DESCRIBE PAYMENT_FOR_TRANSACTION;
DESCRIBE PRODUCT;
DESCRIBE RAISE_TICKET;
DESCRIBE TICKET_DETAILS;
DESCRIBE TRANSACTION;
DESCRIBE TRANSACTION_FOR_ORDER;
DESCRIBE TRANSACTION_MODE;
